### ISSUE TITLE
ETH mainnet EIP-1559 not working? 

### ISSUE THREAD

**Issue by RisingPaw** [RabbyHub/Rabby#920]
Just played with Rabby and sent some basic transactions on ETH mainnet (both from a ledger & from imported seed) and both transactions failed to use the EIP-1559 optimized gas scheme. Looks like it is supposed to be supported.

Any ideas what could be going on? Is there something to activate somewher?

**Comment by vvvvvv1vvvvvv** [comment]
Edit gas -> Advanced Settings, then you can see maxPriorityFee, it's fixed now, will make it automatically soon

<img width="400" alt="image" src="https://user-images.githubusercontent.com/86296331/184592687-1ae5a1df-2057-443f-ae57-c31066fda74f.png">

**Comment by RisingPaw** [comment]
Hey, just to make sure I understand correctly, do I have to change the slider position to activate EIP-1559 (by default it's maxed out)?

Made some transactions again recently and those from Rabby still do not show the EIP-1559 badge on etherscan? While sending the same transaction via MetaMask is properly tagged on etherscan.

Talking about this badge: <img width="87" alt="Screenshot 2022-09-06 at 12 52 13" src="https://user-images.githubusercontent.com/104254327/188617190-a3611219-b31f-480a-86ee-5eb4a5f6e2af.png">

**Comment by belg1o** [comment]
@vvvvvv1vvvvvv Can cofirm, behavior is not as it should be. 
Allow users to set custom default settings supporting EIP-1559 settings.

**Comment by j7an** [comment]
The default behavior is not using EIP-1559 (not going to advanced setting). Could we re-open this issue until fixed? @vvvvvv1vvvvvv

**Comment by vvvvvv1vvvvvv** [comment]
> The default behavior is not using EIP-1559 (not going to advanced setting). Could we re-open this issue until fixed? @vvvvvv1vvvvvv

sure, team will discuss for enable 1559 by default
